version: '3'

services:
  url-shortener:
    image: url-shortener
    hostname: url-shortener
    container_name: url-shortener
    restart: always
    depends_on:
      - url-shortener-db
    build: .
    ports:
      - '8911:8081'
    networks:
      - url-shortener

  url-shortener-db:
    image: mongo
    hostname: url-shortener-db
    container_name: url-shortener-db
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-toor}
    networks:
      - url-shortener

networks:
  url-shortener:
