version: '3'

services:
  url-shortener-db:
    image: mongo
    hostname: url-shortener-db
    container_name: url-shortener-db
    restart: always
    volumes: :
      - './data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-toor}

  url-shortener:
    image: url-shortener
    hostname: url-shortener
    container_name: url-shortener
    restart: always
    depends_on:
      - url-shortener-db
    build: .
    ports:
      - '8911:8081'
